name: Coverage report

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Generate coverage report
      run: |
        pip install pytest-cov
        pytest --cov=mws

    - name: Send report to codecov
      uses: codecov/codecov-action@v1
